<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net472</TargetFramework>
		<Configurations>Debug;Release</Configurations>

		<!-- Metadata -->
		<Authors>Taipei Native</Authors>
		<AssemblyVersion>1.0.0.0</AssemblyVersion> <!--4 digit -->
		<FileVersion>1.0.0</FileVersion> <!--3 digit -->
		<Version>1.0.0</Version> <!--3 digit -->
		
		<!-- The original template didn't specify the language version. -->
		<LangVersion>9.0</LangVersion>
		
		<!--The file where mod information which is required for publishing mod on PDX mods are stored-->
		<PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	
	<!--Imports must be after PropertyGroup block-->
	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />

	<ItemGroup>
		<Reference Include="Game">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Core">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Logging">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.IO.AssetDatabase">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.UI">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.UI.Binding">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Localization">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Burst">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Collections">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Entities">
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Colossal.Collections">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Mathematics">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.PSI.Common">
			<Private>False</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Update="System">
			<Private>False</Private>
		</Reference>
		<Reference Update="System.Core">
			<Private>False</Private>
		</Reference>
		<Reference Update="System.Data">
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Locale\*.json" />
		<Content Remove="Locale\*.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(ModPropsFile)" Link="Properties\Mod.props" />
		<None Include="$(ModTargetsFile)" Link="Properties\Mod.targets" />
	</ItemGroup>

</Project>
